Homework14: Mariya Simonenko
Mary-si/py2024 pull request #14
Opened 2024-06-19 15:48 UTC by Mary-si

2024-06-22 20:17 UTC, Stml89 requested changes

2024-06-22 20:17 UTC, Stml89 commented on homework14_calculator.py
> +        result = eval(compile(a, filename="", mode="eval"))
if you are going with this, please add validation

2024-06-22 20:17 UTC, Stml89 commented on homework14_file.py
> +    students_by_group: dict[str, list['Students']] = {}
1/ Use type hints everywhere or nowhere
2/ store and read all information from file

2024-06-22 20:17 UTC, Stml89 commented on homework14_file.py
> +        """общая информация о студентах"""
```suggestion
        """общая информация о студенте"""
```

2024-06-22 20:17 UTC, Stml89 commented on homework14_file.py
> +            STUDENT_INFO = str(student)
STUDENT_INFO in uppercase?
```suggestion
            STUDENT_INFO = str(student)
```

2024-06-24 09:34 UTC, Mary-si commented on homework14_calculator.py
> +        result = eval(compile(a, filename="", mode="eval"))
поправила

2024-06-24 09:34 UTC, Mary-si commented on homework14_file.py
> +    students_by_group: dict[str, list['Students']] = {}
поправила

2024-06-24 09:35 UTC, Mary-si commented on homework14_file.py
> +        """общая информация о студентах"""
поправила

2024-06-28 20:49 UTC, Stml89 approved these changes

2024-06-29 21:58 UTC, merged