Homework18: Mariya Simonenko
Mary-si/py2024 pull request #15
Opened 2024-07-16 22:21 UTC by Mary-si

2024-07-19 20:49 UTC, Stml89 reviewed
Remove `.idea` folder

2024-07-19 20:49 UTC, Stml89 commented on .github/.DS_Store
remove this file

2024-07-19 20:49 UTC, Stml89 commented on .DS_Store
remove this file

2024-07-19 20:49 UTC, Stml89 commented on .idea/.DS_Store
remove this file

2024-07-19 20:49 UTC, Stml89 commented on homework11_bank_deposit.py
> +class Deposit:  # pylint: disable=too-few-public-methods
```suggestion
class Deposit:
```

2024-07-19 20:49 UTC, Stml89 commented on tests_homework11_library.py
> +    #                      "id_number должен состоять из 7 цифр")
Remove it

2024-07-22 22:51 UTC, Mary-si commented on homework11_bank_deposit.py
> +class Deposit:  # pylint: disable=too-few-public-methods
но тогда пишет ошибку
<img width="768" alt="Снимок экрана 2024-07-23 в 01 49 34" src="https://github.com/user-attachments/assets/b355a608-2366-4659-9eca-e5d21e90d59c">

2024-07-22 22:51 UTC, Mary-si commented on .idea/.DS_Store
+

2024-07-22 22:51 UTC, Mary-si commented on .DS_Store
+

2024-07-22 22:51 UTC, Mary-si commented on .github/.DS_Store
+

2024-07-22 22:51 UTC, Mary-si commented on tests_homework11_library.py
> +    #                      "id_number должен состоять из 7 цифр")
+

2024-07-23 19:39 UTC, Stml89 requested changes

2024-07-23 19:39 UTC, Stml89 commented on homework11_bank_deposit.py
> +class Deposit:  # pylint: disable=too-few-public-methods
вместо этой строчки, пробовала добавить это исключение в `pylint.yaml` файл?

2024-07-28 07:36 UTC, Mary-si commented
проверь пожалуйста

2024-08-02 20:53 UTC, Stml89 requested changes
Overall, HW looks good, but you need to fix the comments and remove the `.idea` directory. I marked it with 5, but when you fix the comments, I'll revise the grade.

2024-08-02 20:53 UTC, Stml89 commented on homework11_library.py
> +user_2.reservation_book(book_2)
```suggestion
if __name__ == "__main__":
  user_1 = User("Mariya", "Simonenko", 1234589)
  user_2 = User("Ivan", "Ivanov", 8944589)
  user_3 = User("Olya", "Ignatenko", 2374549)
  
  # Проверка
  user_1.take_book(book_1)
  user_3.take_book(book_1)
  user_1.return_book(book_1)
  user_2.reservation_book(book_2)
```

2024-08-02 20:53 UTC, Stml89 commented on homework11_bank_deposit.py
> +      f"будет {final_amount_user_1:.2f} рублей")
```suggestion
if __name__ == '__main__':
    user_1 = Bank(20000, 4, 0.05)
    user_2 = Bank(5000, 3, 0.03)
    user_3 = Bank(2000, 1, 0.01)
    
    # Проверка
    final_amount_user_1 = user_1.calculate()
    print(f"Сумма на счету у пользователя {user_1.deposit_term_year} лет,"
          f"будет {final_amount_user_1:.2f} рублей")
```

2024-08-15 19:02 UTC, Stml89 approved these changes

2024-08-22 07:44 UTC, merged