Homework7: Mariya Simonenko
Mary-si/py2024 pull request #4
Opened 2024-05-28 14:15 UTC by Mary-si

2024-05-28 21:24 UTC, Stml89 requested changes

2024-05-28 21:24 UTC, Stml89 commented on homework7_statues.py
> +# отсортировать от меньшего к большему
pls, do not comment on obvious actions

2024-05-28 21:24 UTC, Stml89 commented on homework7_statues.py
> +print(statues)
you do not need to print every actions

2024-05-28 21:24 UTC, Stml89 commented on homework7_statues.py
> +statues.sort()
you do not need to sort a list, find min and max values and integrate from min to max

2024-05-28 21:24 UTC, Stml89 commented on homework7_bulls_and_cows.py
> +            # len - длинна строки
do not write comments for obvious actions

2024-05-28 21:24 UTC, Stml89 commented on homework7_bulls_and_cows.py
> +def get_all_answers():
you have generated a lot of data, it requires memory and time, it is much easier to use randint and shuffle methods from random library

2024-05-28 21:24 UTC, Stml89 commented on homework7_bulls_and_cows.py
I'm not sure that I understood the logic of this program. could you please explain it

2024-05-29 09:30 UTC, Mary-si commented on homework7_bulls_and_cows.py
1.  игрок загадывает число
2. компьтер загадывает число
3. поочередно вводим предполагаемы числа (сначала игрок, затем компьютер)
4. сообщаем в ответе сколько цифр и позиций угадано
5. компьютер вывод предполагаемое число ктр загадал игрок
6. если компьютер не угадал, он исключает все возможные комбинации с цифрами ктр он не угадал
7. продолжаем играем до победы

2024-05-29 09:35 UTC, Mary-si commented on homework7_bulls_and_cows.py
> +def get_all_answers():
должно быть так?

import random
digits = random.sample("0123456789", 4)
print(int("".join(digits)))

2024-05-29 09:41 UTC, Mary-si commented on homework7_statues.py
> +statues.sort()
я сортирую от мин к макс, чтобы понять:
1. как выглядит наш список
2. какое значение на 0ой и последней позиции (это нужно для конечно подсчета сколько не хватает)

или это по другому надо было делать?)

2024-05-29 20:28 UTC, Stml89 commented on homework7_bulls_and_cows.py
> +def get_all_answers():
yes, this is one possible approach

2024-05-29 20:28 UTC, Stml89 commented on homework7_statues.py
> +statues.sort()
you can find MIN value and MAX value, based on this data create a list from [MIN..MAX]

2024-05-30 16:52 UTC, Mary-si commented on homework7_statues.py
> +statues.sort()
исправила

2024-05-30 16:52 UTC, Mary-si commented on homework7_bulls_and_cows.py
> +def get_all_answers():
исправила

2024-05-31 19:38 UTC, Stml89 approved these changes

2024-06-01 11:02 UTC, merged