Homework8: Mariya Simonenko
Mary-si/py2024 pull request #5
Opened 2024-05-30 16:58 UTC by Mary-si

2024-05-31 20:25 UTC, Stml89 requested changes

2024-05-31 20:25 UTC, Stml89 commented on homework8_opposite_number.py
> +FIRST_NUMBER = 2
you hardcoded numbers, what if I want to use another number?

2024-05-31 20:25 UTC, Stml89 commented on homework8_opposite_number.py
> +# a = list(range(n))
Pls, do not leave commented code in the repository

2024-05-31 20:25 UTC, Stml89 commented on homework8_subsequence.py
use function to remove duplication

2024-05-31 20:25 UTC, Stml89 commented on homework8_validate.py
> +    # сумма чисел
pls, do to write comment to obvious code

2024-06-01 11:21 UTC, Mary-si commented on homework8_opposite_number.py
> +FIRST_NUMBER = 2
а для этого мы и нашли "закономерность" (B = N//2, 2 - это не первое число ввода). если подставляем для N и FIRST_NUMBER др значения, то тоже работает)))
<img width="856" alt="Снимок экрана 2024-06-01 в 14 19 57" src="https://github.com/Mary-si/py2024/assets/168018982/3887b7ba-953e-408b-975b-06518ab4efa2">

2024-06-01 11:21 UTC, Mary-si commented on homework8_opposite_number.py
> +# a = list(range(n))
исправила

2024-06-01 11:27 UTC, Mary-si commented on homework8_opposite_number.py
> +FIRST_NUMBER = 2
а для этого мы и находим "закономерность". нашла ошибку, подправила код. вроде работает)
<img width="363" alt="Снимок экрана 2024-06-01 в 14 25 58" src="https://github.com/Mary-si/py2024/assets/168018982/c870fb0d-6fd5-423b-af04-55d831b3328e">

2024-06-01 18:01 UTC, Stml89 requested changes

2024-06-01 18:01 UTC, Stml89 commented on homework8_opposite_number.py
> +FIRST_NUMBER = 2
use `input()` to request user to enter number

2024-06-04 12:10 UTC, Mary-si commented on homework8_opposite_number.py
> +FIRST_NUMBER = 2
исправила

2024-06-06 19:47 UTC, Stml89 approved these changes
Approved, merge PR

2024-06-10 21:50 UTC, merged