Homework9: Mariya Simonenko
Mary-si/py2024 pull request #6
Opened 2024-06-04 16:36 UTC by Mary-si

2024-06-06 20:27 UTC, Stml89 requested changes

2024-06-06 20:27 UTC, Stml89 commented on homework9_candles.py
> +print(solution(2, 3))
remove line#46-52

2024-06-06 20:27 UTC, Stml89 commented on homework9_symbo1.py
> +print(symbols("a#bc#d"))
use `assert` instead of `print`

2024-06-06 20:27 UTC, Stml89 commented on homework9_symbol.py
> +    for [_, s] in enumerate(a):
since you are not using `index`, you can iterate over a string:
`
for i in a:
...
`

2024-06-06 20:27 UTC, Stml89 commented on homework9_symbol.py
> +        if symbol != s:
`elif` here, symbol can be the the on not?

2024-06-13 12:14 UTC, Mary-si commented on homework9_symbo1.py
> +print(symbols("a#bc#d"))
поправила

2024-06-13 12:14 UTC, Mary-si commented on homework9_symbol.py
> +        if symbol != s:
поправила

2024-06-16 17:40 UTC, Stml89 approved these changes

2024-06-16 19:52 UTC, merged