Homework10: Mariya Simonenko
Mary-si/py2024 pull request #7
Opened 2024-06-06 14:00 UTC by Mary-si

2024-06-07 05:41 UTC, Stml89 commented
Hello @Mary-si , the pylint fails PR because of space in the filename:
<img width="320" alt="image" src="https://github.com/Mary-si/py2024/assets/4534254/d91f2e3c-b691-4a46-a558-e7ab86135aeb">

2024-06-07 09:35 UTC, Mary-si commented
спасибо((((

2024-06-07 22:30 UTC, Stml89 requested changes

2024-06-07 22:30 UTC, Stml89 commented on homework10_caching_func.py
> +print(fibonacci(5))  # Вывод: 5
Use `assert` to check your code

2024-06-07 22:30 UTC, Stml89 commented on homework10_type_decorator.py
> +def typed1(expected_type):
it should be 1 decorator that supports different amount of arguments

2024-06-10 21:42 UTC, Mary-si commented on homework10_caching_func.py
> +print(fibonacci(5))  # Вывод: 5
поправила

2024-06-10 21:42 UTC, Mary-si commented on homework10_type_decorator.py
> +def typed1(expected_type):
поправила

2024-06-19 11:19 UTC, merged