Homework11: Mariya Simonenko
Mary-si/py2024 pull request #8
Opened 2024-06-10 18:07 UTC by Mary-si

2024-06-10 21:07 UTC, Mary-si commented
можно уточнить как правильно указать "flag"? чтобы pylint не ругался?

2024-06-13 12:52 UTC, Mary-si commented
поправила

2024-06-16 09:07 UTC, Stml89 requested changes

2024-06-16 09:07 UTC, Stml89 commented on homework11_library.py
> +        # True - доступна. False - взята. None - зарезервирована
a bit complex. It is better to introduce 1 more flag: is_reserved to show reserved status

```
self.is_available = True
self.is_reserved = True
```

2024-06-16 09:07 UTC, Stml89 commented on homework11_library.py
> +    # def check_status_book(self):
if you will not use it - remove

2024-06-16 09:07 UTC, Stml89 commented on homework11_library.py
> +    def returned(self):
this method doesn’t return the value, it SET value, better to rename it

2024-06-16 09:07 UTC, Stml89 commented on homework11_library.py
> +        if self.status is True:
`if self.status:`

2024-06-16 09:07 UTC, Stml89 commented on homework11_library.py
> +# Проверка
user_1 took a book, but user_3 can return the same book? But user_3 didn't take this book:
```
user_1.take_book(book_1)
user_3.return_book(book_1)
```

2024-06-16 21:14 UTC, Mary-si commented on homework11_bank_deposit.py
> +deposit_1 = Deposit("08.09.2021", "08.09.2025")
поправила

2024-06-16 22:20 UTC, Mary-si commented on homework11_library.py
> +# Проверка
тут имелось ввиду показать User_3  что книга уже взята
поправила.

2024-06-16 22:20 UTC, Mary-si commented on homework11_library.py
> +    # def check_status_book(self):
+

2024-06-16 22:20 UTC, Mary-si commented on homework11_library.py
> +        # True - доступна. False - взята. None - зарезервирована
поправила

2024-06-17 17:38 UTC, Stml89 commented on homework11_bank_deposit.py
> +class Deposit:  # pylint: disable=too-few-public-methods
What about this comment?

2024-06-17 17:39 UTC, Stml89 commented
There is a conflict, to be able to merge this PR you need to resolve conflict first https://docs.github.com/ru/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github

2024-06-19 10:48 UTC, Mary-si commented on homework11_bank_deposit.py
> +class Deposit:  # pylint: disable=too-few-public-methods
удалила, это пробовала чтобы pylint не ругался

2024-06-19 10:49 UTC, Mary-si commented on homework11_library.py
> +        if self.status is True:
поправила

2024-06-20 20:54 UTC, Stml89 commented
> There is a conflict, to be able to merge this PR you need to resolve conflict first https://docs.github.com/ru/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github

Still need to resole a conflict

2024-06-24 08:47 UTC, Mary-si commented
> > There is a conflict, to be able to merge this PR you need to resolve conflict first https://docs.github.com/ru/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github
> 
> Still need to resole a conflict, if need assistance let me know

надо попробовать 
![2024-06-24 11 46 32](https://github.com/Mary-si/py2024/assets/168018982/2b7506f6-1906-4c84-baf9-e34010e28a97)
![2024-06-24 11 46 38](https://github.com/Mary-si/py2024/assets/168018982/0936df65-0429-444f-a906-c28d796a7324)
выбрать это?

2024-06-26 04:49 UTC, Stml89 commented
Давай посмотрим что он скажет на "create a merge commit"

2024-06-29 23:00 UTC, Mary-si commented
+

2024-07-01 14:22 UTC, Stml89 requested changes

2024-07-01 14:22 UTC, Stml89 commented on .github/.DS_Store
remove this file from the repo, should be in the `.gitignore`

2024-07-01 14:22 UTC, Stml89 commented on .DS_Store
remove this file from the repo, should be in the `.gitignore`

2024-07-04 10:07 UTC, Mary-si commented
поправила

2024-07-05 20:18 UTC, Stml89 commented
> поправила

I still can see a lot of extra files and directories in the repository

2024-07-10 16:08 UTC, Mary-si commented
> > поправила
> 
> I still can see a lot of extra files and directories in the repository

не так должно быть?
<img width="968" alt="Снимок экрана 2024-07-10 в 19 07 56" src="https://github.com/Mary-si/py2024/assets/168018982/da5dee08-9425-4c75-8a0d-bad5d537cca2">

2024-07-14 21:23 UTC, Mary-si commented
добавила 
<img width="437" alt="Снимок экрана 2024-07-15 в 00 18 06" src="https://github.com/user-attachments/assets/f5abc785-6cdf-42bb-bcf3-1bc6a42bebc1">

2024-07-16 19:15 UTC, Stml89 commented
Привет, репозиторий должен быть чистым, а это значит, что:
надо удалить:
1) .github/.DS_Store
2) Папку .venv
3) .DS_Store
4) Папку .idea

2024-07-19 20:53 UTC, Stml89 requested changes
what is the differences between
1) `homework11_library1.py` and homework11_library.py?
2) `homework11_bank_deposits.py` and `homework11_bank_deposit.py`

2024-07-19 20:53 UTC, Stml89 commented on .idea/.DS_Store
remove this file

2024-07-19 20:53 UTC, Stml89 commented on .github/.DS_Store
remove this file

2024-07-19 20:53 UTC, Stml89 commented on .DS_Store
remove this file

2024-07-19 20:53 UTC, Stml89 commented on .gitignore
pls, restore this file. it tracks what should be in the repo and wise versa

2024-07-28 07:28 UTC, Mary-si commented
вроде все проверь пожалуйста

2024-08-02 20:42 UTC, Stml89 requested changes
Overall, HW looks good, but you need to fix the comments and remove the `.idea` directory. I marked it with 5, but when you fix the comments, I'll revise the grade.

2024-08-02 20:42 UTC, Stml89 commented on .github/.DS_Store
Move it to `.gitignore`

2024-08-02 20:42 UTC, Stml89 commented on .DS_Store
Move it to `.gitignore`

2024-08-13 16:42 UTC, Mary-si commented on .DS_Store
я вроде сделала, но не понимаю

2024-08-15 19:04 UTC, Stml89 approved these changes

2024-08-22 07:35 UTC, merged