Homework12: Mariya Simonenko
Mary-si/py2024 pull request #9
Opened 2024-06-18 21:37 UTC by Mary-si

2024-06-21 19:14 UTC, Stml89 commented
You still have 4 files in a conflict state, this should be fixed. What is more, a lot of files from previous PRs, so your branch is not based on `master`\`main` branch

2024-06-21 19:25 UTC, Stml89 requested changes

2024-06-21 19:25 UTC, Stml89 commented on homework12_cards.py
> +        self.cards.extend([Card("Joker", None) for _ in range(2)])  # Добавляем двух джокеров
```suggestion
        self.cards.extend([Card("Joker", "Red")])
        self.cards.extend([Card("Joker", "Black")])
```

2024-06-21 19:25 UTC, Stml89 commented on homework12_cards.py
> +        return f"{self.number} {self.mast}" if self.mast else f"{self.number}"
```suggestion
        return f"{self.number} {self.mast}"
```

2024-06-21 19:25 UTC, Stml89 commented on homework12_converter.py
> +assert Currency.exchange_currency(petya.currency, petya.amount) == (10.76, "USD"), "Ошибка конвертации в USD"
have you tried to run this program, it does not work =(

2024-06-21 19:25 UTC, Stml89 commented on homework9_candles.py
File(s) related to prev HW

2024-06-21 19:25 UTC, Stml89 commented on homework12_molecules.py
> +    """возвращает строко, ктр состоит из символов элемента"""
typos in doc string

2024-06-21 19:25 UTC, Stml89 commented on homework12_molecules.py
> +def molecule(formula: str) -> dict:
Brackets also can be `{` `}`

2024-06-29 22:51 UTC, Mary-si commented
+

2024-07-01 20:19 UTC, Stml89 commented
1\ add `.idea` to the `.gitignore` file. 
2\ Fix comments above

2024-07-01 20:20 UTC, Stml89 requested changes
Comment above

2024-07-04 10:01 UTC, Mary-si commented
отредактировала

2024-07-22 22:53 UTC, Mary-si commented
тут ок?

2024-07-23 19:48 UTC, Stml89 commented
как минимум надо удалить папку `.idea` из репозитория

2024-07-28 07:32 UTC, Mary-si commented
проверь пожалуйста

2024-08-02 20:57 UTC, Stml89 requested changes
Overall, HW looks good, but you need to fix the comments and remove the `.idea` directory. I marked it with 6, but when you fix the comments, I'll revise the grade.

2024-08-13 16:47 UTC, Mary-si commented
еще раз глянь

2024-08-15 19:05 UTC, Stml89 approved these changes

2024-08-22 07:40 UTC, merged